#! /usr/bin/bash


# update & upgrade
sudo apt-get update
sudo apt-get dist-upgraede -y

# others
sudo -H python3 -m pip install ROPgadget    # ROPgdget
sudo gem install one_gadget                 # one_gadget

# setup list
declare -a setup_list=(
    # tools
    git
    python3-pip
    tmux
    thefuck
    ruby
    # pwn
    checksec
    ltrace
    strace
)

# pip list
declare -a pip_list=(
    pwntools
)


# setup_lisr install
for i in "${setup_list[@]}"
do
    sudo apt-get install "$i"
done

# pip_list install
for i in "${pip_list[@]}"
do
    sudo pip install "$i"
done



