#! /usr/bin/bash


# update & upgrade
sudo apt-get update
sudo apt-get dist-upgrade -y

# others
sudo -H python3 -m pip install ROPgadget    # ROPgdget
sudo gem install one_gadget                 # one_gadget

# setup list
# setup list
declare -a setup_list=(
    # tools
    python3-pip
    tmux
    thefuck
    ruby
    vim
        # you can add something you want to use "sudo apt-get install" to install here.

)
# pip list
declare -a pip_list=(
        # you can add something you want to use "sudo pip install" to  install here. 
)

# setup_list install
for i in "${setup_list[@]}"
do
    sudo apt-get install "$i"
done

# pip_list install
for i in "${pip_list[@]}"
do
    sudo pip install "$i"
done



