"""""""""""""""""""""""Vundle""""""""""""""""""""""""""
""" source : https://github.com/VundleVim/Vundle.vim
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'


Plugin 'preservim/nerdtree'
Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'vim-airline/vim-airline'
Plugin 'flazz/vim-colorschemes'
Plugin 'valloric/youcompleteme'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Basic Settinig
syntax enable          " enable syntax highlight
set number             " display lines number
set t_Co=256           " supports 256 colors
set background=dark    " setting background
set hlsearch           " search highlight
set ts=4               " tabstop = 4
set autoindent 		   " autoindent : autoindent/smartindent/cindne
colorscheme atom-dark  " colorscheme : slate/molokai

" filetype
filetype on
filetype indent on
filetype plugin on

" line-column
set cursorline
set cursorcolumn
set encoding=UTF-8
let g:airline_powerline_fonts = 1
set guifont=DroidSansMono\ Nerd\ Font\ 11
let NERDTreeShowHidden=1


hi CursorLine cterm=underline ctermbg=none ctermfg=White
hi CursorColumn cterm=none ctermbg=Gray ctermfg=White

""""""""""""""""""""""hot key""""""""""""""""""""""""""
nnoremap <silent> <C-b> :NERDTreeToggle <CR>
vmap <C-c> y
nmap <C-v> p
